name: AndroidBuild

on:
  pull_request:
    branches: [ main, Develop ]
  push:
    branches: [ main, Develop, feature-cicd-implement ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set Up JDK
        uses: actions/setup-java@v4.1.0
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Change gradle permissions
        run: chmod +x ./gradlew

      - name: Run Integration Tests
        run: ReactiveCircus/android-emulator-runner@v2.30.1
        with:
          api-level: 33
          emulator-build: 7425822
          script: ./gradlew connectedDevDebugAndroidTest --stacktrace
          emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -skin 1920x1080
          disable-animations: true
          disable-spellchecker: true

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Build Project
        run: ./gradlew assemble